### ISSUE TITLE
Intermittent errors when downloading sqlcl or java

### ISSUE THREAD

**Issue by navratil** [gvenzl/setup-oracle-sqlcl#5]
We using [setup-oracle-sqlcl](https://github.com/gvenzl/setup-oracle-sqlcl) in our pipeline since January and it has been working great.

In the last two weeks we started to experience intermittent errors downloading sqlcl/java errors - it's crashing about 50% of our CI runs 

I appreciate this may not be directly related to the setup-oracle-sqlcl itself - any guidance would be helpful.

---
Run gvenzl/setup-oracle-sqlcl@v1
Run actions/setup-java@v3
Installed distributions
Creating settings.xml with server-id: github
Overwriting existing file /home/gh-runner/.m2/settings.xml
Run ${GITHUB_ACTION_PATH}/verify_java.sh
☕️ Verifying Java Version
Run ${GITHUB_ACTION_PATH}/setup_sqlcl.sh
📦 Download SQLcl
  ✅ Located versions mapper file
  ⬇️ Downloading https://download.oracle.com/otn_software/java/sqldeveloper/sqlcl-latest.zip
  ☠️  SQLcl could not be downloaded/copied
  java.net.SocketException: Connection reset
  	at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:328)
  	at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:355)
  	at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:808)
  	at java.base/java.net.Socket$SocketInputStream.read(Socket.java:966)

---
Run gvenzl/setup-oracle-sqlcl@v1
Run actions/setup-java@v3
Installed distributions
  Trying to resolve the latest version from remote
  Resolved latest version as 17
  Trying to download...
  Downloading Java 17 (Oracle) from https://download.oracle.com/java/17/latest/jdk-17_linux-aarch64_bin.tar.gz ...
  aborted
  Waiting 17 seconds before trying again
  aborted
  Waiting [10](https://github.com/amos-ie/university-skills-passport/actions/runs/10508969848/job/29114046250#step:4:11) seconds before trying again
  Error: aborted

**Comment by aalmiray** [comment]
Perhaps we need to bump the action to use Java 21 instead of 17. 

In the mean time you may use the `setup-java-version` property to override the default value of 17.

**Comment by navratil** [comment]
Happy to report we have not experienced this issue since we switched to Java 21 (4 days ago)
Thank you!

**Comment by aalmiray** [comment]
Thank you for the feedback. We'll update the default setting to 21 in the coming days.

**Comment by navratil** [comment]
We're experiencing it again with Java 21 - perhaps the CloudWorld effect :-)

---

Run gvenzl/setup-oracle-sqlcl@v1
  
Run actions/setup-java@v3
  
Installed distributions
  Trying to resolve the latest version from remote
  Resolved latest version as 21
  Trying to download...
  Downloading Java 21 (Oracle) from https://download.oracle.com/java/21/latest/jdk-21_linux-aarch64_bin.tar.gz ...
  aborted
  Waiting 10 seconds before trying again
  aborted
  Waiting 19 seconds before trying again
  Error: aborted

**Comment by aalmiray** [comment]
This might be something else. Let me check what it could be.

**Comment by aalmiray** [comment]
Here's an update https://github.com/oracle-actions/setup-java/issues/86

Once addressed we'll update our dependencies and post a release.

**Comment by gvenzl** [comment]
This has been addressed in the upstream oracle-actions/setup-java action
